### ISSUE TITLE
data/ai.lua:464: attempt to index field 'target' (a nil value)

### ISSUE THREAD

**Issue by Rorkh** [vaughantay/roguelove#5]
Got this error when played, attacked the enemy.
I was unable to copy error (Ctrl + C or tap didn't worked) so I wrote some part of it by hand (to copy and navigate to main error functions) and attached the screenshot

```
Error

data/ai.lua:464: attempt to index field 'target' (a nil value)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
data/ai.lua:464: in function 'moveAlongPath'
data/ai.lua:140: in function 'basic'
classes/creature.lua:937: in function 'advance'
```

![image](https://github.com/vaughantay/roguelove/assets/78957156/e85260bd-7fef-4c74-bc28-fc8afa0c9e75)

**Comment by vaughantay** [comment]
I'm not 100% certain what caused the error but I believe I just pushed a change to data/ai.lua that fixes it.
If it reoccurs with the same save (should have autosaved right before the crash), could you post the save?
Linux: ~/.local/share/love/rogueloveexample/
Windows: C:\Users(YourUserName)\AppData\Roaming\LOVE\rogueloveexample\
Mac: ~/Library/Application Support/love/rogueloveexample/

**Comment by Rorkh** [comment]
Save
[error 2023-08-04 00-17-10.txt](https://github.com/vaughantay/roguelove/files/12260068/error.2023-08-04.00-17-10.txt)

**Comment by Rorkh** [comment]
Save (added txt to end of filename so I can send it)
[Pornographic S.-error-2023-08-04 00-17-10.sav.txt](https://github.com/vaughantay/roguelove/files/12260075/Pornographic.S.-error-2023-08-04.00-17-10.sav.txt)

**Comment by vaughantay** [comment]
Are you still getting the crash with the updated ai.lua? I could get it to occur without the updated code, but not with the updated  code.

**Comment by Rorkh** [comment]
> Are you still getting the crash with the updated ai.lua? I could get it to occur without the updated code, but not with the updated code.

Seems like it's fixed
